In [9]:
import numpy as np

In [10]:
a = np.array([1, 2, 3, 4])
a + 1
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [11]:
b = np.ones(4) + 1
a - b
a * b
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [12]:
a = np.arange(10000)
%timeit a + 1
l = range(10000)
%timeit [i+1 for i in l] 

25.7 µs ± 280 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
2.62 ms ± 160 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

a > b

array([False, False,  True, False])

In [14]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)

np.logical_and(a, b)

array([ True, False, False, False])

In [15]:
a = np.arange(5)
np.sin(a)

np.log(a)

np.exp(a)

c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [16]:
a = np.arange(4)
a + np.array([1, 2])  

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [17]:
a = np.triu(np.ones((3, 3)), 1)   # see help(np.triu)
a
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [18]:
x = np.array([1, 2, 3, 4])
np.sum(x)

x.sum()

10

In [19]:
x = np.array([[1, 1], [2, 2]])
x
x.sum(axis=0)   # columns (first dimension)
x[:, 0].sum(), x[:, 1].sum()
x.sum(axis=1)   # rows (second dimension)
x[0, :].sum(), x[1, :].sum()

(2, 4)

In [20]:
x = np.random.rand(2, 2, 2)
x.sum(axis=2)[0, 1]
x[0, 1, :].sum()

1.5535748723316027

In [21]:
x = np.array([1, 3, 2])
x.min()

x.max()


x.argmin()  # index of minimum

x.argmax()  # index of maximum

1

In [22]:
np.all([True, True, False])

np.any([True, True, False])

True

In [23]:
a = np.zeros((100, 100))
np.any(a != 0)

np.all(a == a)


a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

In [24]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

np.median(x)

np.median(y, axis=-1) # last axis


x.std()          # full population standard dev.

0.82915619758885

In [54]:

data = np.loadtxt('data/populations.txt')
year, hares, lynxes, carrots = data.T  # trick: columns to variables

OSError: data/populations.txt not found.

In [ ]:
from matplotlib import pyplot as plt
plt.axes([0.2, 0.1, 0.5, 0.8]) 
plt.plot(year, hares, year, lynxes, year, carrots) 
plt.legend(('Hare', 'Lynx', 'Carrot'), loc=(1.05, 0.5))

In [ ]:
populations = data[:, 1:]
populations.mean(axis=0)

In [ ]:
populations.std(axis=0)

In [30]:
np.argmax(populations, axis=1)

NameError: name 'populations' is not defined

In [31]:
n_stories = 1000 # number of walkers
t_max = 200      # time during which we follow the walker

In [32]:
t = np.arange(t_max)
steps = 2 * np.random.randint(0, 1 + 1, (n_stories, t_max)) - 1 # +1 because the high value is exclusive
np.unique(steps) # Verification: all steps are 1 or -1

array([-1,  1])

In [33]:
positions = np.cumsum(steps, axis=1) # axis = 1: dimension of time
sq_distance = positions**2

In [34]:
mean_sq_distance = np.mean(sq_distance, axis=0)

In [35]:
plt.figure(figsize=(4, 3)) 

plt.plot(t, np.sqrt(mean_sq_distance), 'g.', t, np.sqrt(t), 'y-') 

plt.xlabel(r"$t$") 

plt.ylabel(r"$\sqrt{\langle (\delta x)^2 \rangle}$") 

plt.tight_layout() # provide sufficient space for labels

NameError: name 'plt' is not defined

In [36]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
a
b = np.array([0, 1, 2])
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [37]:
a = np.ones((4, 5))
a[0] = 2  # we assign an array of dimension 0 to an array of dimension 1
a

array([[2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
a = np.arange(0, 40, 10)
a.shape

a = a[:, np.newaxis]  # adds a new axis -> 2D array
a.shape

a
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [39]:
mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544,
       1913, 2448])
distance_array = np.abs(mileposts - mileposts[:, np.newaxis])
distance_array

array([[   0,  198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448],
       [ 198,    0,  105,  538,  673,  977, 1277, 1346, 1715, 2250],
       [ 303,  105,    0,  433,  568,  872, 1172, 1241, 1610, 2145],
       [ 736,  538,  433,    0,  135,  439,  739,  808, 1177, 1712],
       [ 871,  673,  568,  135,    0,  304,  604,  673, 1042, 1577],
       [1175,  977,  872,  439,  304,    0,  300,  369,  738, 1273],
       [1475, 1277, 1172,  739,  604,  300,    0,   69,  438,  973],
       [1544, 1346, 1241,  808,  673,  369,   69,    0,  369,  904],
       [1913, 1715, 1610, 1177, 1042,  738,  438,  369,    0,  535],
       [2448, 2250, 2145, 1712, 1577, 1273,  973,  904,  535,    0]])

In [40]:
x, y = np.arange(5), np.arange(5)[:, np.newaxis]
distance = np.sqrt(x ** 2 + y ** 2)
distance

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [4.        , 4.12310563, 4.47213595, 5.        , 5.65685425]])

In [41]:
plt.pcolor(distance)    
plt.colorbar()

NameError: name 'plt' is not defined

In [42]:
x, y = np.ogrid[0:5, 0:5]
x, y

x.shape, y.shape
distance = np.sqrt(x ** 2 + y ** 2)

In [43]:
x, y = np.ogrid[0:5, 0:5]
x, y

x.shape, y.shape
distance = np.sqrt(x ** 2 + y ** 2)

In [44]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()
a.T
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [45]:
a.shape

b = a.ravel()
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
a.reshape((2, -1))    # unspecified (-1) value is inferred

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
b[0, 0] = 99
a

array([[99,  2,  3],
       [ 4,  5,  6]])

In [48]:
a = np.zeros((3, 2))
b = a.T.reshape(3*2)
b = a.T.reshape(3*2)
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [49]:
z = np.array([1, 2, 3])
z
z[:, np.newaxis]
z[np.newaxis, :]

array([[1, 2, 3]])

In [50]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

a[0, 2, 1]

b = a.transpose(1, 2, 0)
b.shape

b[2, 1, 0]

5

In [51]:
b[2, 1, 0] = -1
a[0, 2, 1]

-1

In [52]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [53]:
b = a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False